version: '3'

services:
  web:
    build:
      context: .
      dockerfile: golang.Dockerfile
    image: web
    container_name: web
    restart: always
    ports:
      - '8060:8060'
    environment:
      - NAME_WEB=web
      - PORT=8060
    network_mode: "host"
