version: '3'

services:
  proxy:
    ports:
      - '80:80'
    environment:
      - NGINX_SERVER_NAME=worker

  consul:
    ports:
      - '8500:8500'
    environment:
      - NODE_NAME=worker
      - BIND_IP=192.168.60.10

  blue:
    image: ${current_image}
    ports:
      - '8060:8060'

  green:
    image: ${current_image}
    ports:
      - '8070:8070'
