version: '3'

services:
  proxy:
    ports:
      - '80:80'
    environment:
      - NGINX_SERVER_NAME=worker

  consul:
    ports:
      - '8500:8500'
    environment:
      - NODE_NAME=worker
      - BIND_IP=192.168.60.10

  blue:
    image: mattmyers3491/jenkins-test:latest
    ports:
      - '8060:8060'
    environment:
      - NAME_WEB=blue
      - PORT=8060

  green:
    image: mattmyers3491/jenkins-test:latest
    ports:
      - '8070:8070'
    environment:
      - NAME_WEB=green
      - PORT=8070
